# Generated by Django 5.2.10 on 2026-01-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_remove_post_slug_post_comic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
