# Generated by Django 5.2.10 on 2026-01-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='publish'),
        ),
    ]
